version: '3.8'

services:
  kong-database:
    image: postgres:13
    container_name: kong-database
    environment:
      POSTGRES_USER: kong
      POSTGRES_DB: kong
      POSTGRES_PASSWORD: kong
    networks:
      - kong-net
    volumes:
      - kong-database-data:/var/lib/postgresql/data

  kong-migration:
    image: custom-kong:3.0
    container_name: kong-migration
    depends_on:
      - kong-database
    environment:
      KONG_DATABASE: postgres
      KONG_PG_HOST: kong-database
      KONG_PG_USER: kong
      KONG_PG_PASSWORD: kong
    networks:
      - kong-net
    command: kong migrations bootstrap

  kong:
    image: custom-kong:3.0
    container_name: kong
    depends_on:
      - kong-database
      - kong-migration
    # volumes:
    #   # - ~/kong_chalenge/kong-plugin-soap-request-transformer-master:/usr/local/share/lua/5.1/kong/plugins/kong-plugin-soap-request-transformer-master  # Montage du répertoire local du plugin
    #   - ~/kong_chalenge/kong-plugin-soap-request-transformer-master/kong/plugins/soap-request-transformer:/usr/local/share/lua/5.1/kong/plugins/soap-request-transformer # Montage du fichier rockspec
    environment:
      KONG_DATABASE: postgres
      KONG_PG_HOST: kong-database
      KONG_PG_USER: kong
      KONG_PG_PASSWORD: kong
      KONG_PROXY_ACCESS_LOG: /dev/stdout
      KONG_ADMIN_ACCESS_LOG: /dev/stdout
      KONG_PROXY_ERROR_LOG: /dev/stderr
      KONG_ADMIN_ERROR_LOG: /dev/stderr
      KONG_ADMIN_LISTEN: 0.0.0.0:8001, 0.0.0.0:8444 ssl
      KONG_PLUGINS: bundled,soap-request-transformer  # Ajouter le plugin soap-request-transformer à la liste des plugins
    ports:
      - "8000:8000"
      - "8443:8443"
      - "8001:8001"
      - "8444:8444"
    networks:
      - kong-net
  soap-service:
    image: kamiait/soap-service:1.0
    container_name: soap.service.com
    hostname: soap.service.com
    networks:
      - kong-net
    ports:
      - "5000:5000"  # Exposer le port interne 5000
    restart: always   

networks:
  kong-net:
    driver: bridge

volumes:
  kong-database-data:
